namespace RefactorGraph
{
    public enum RefactorNodeType
    {
        GetDocument,
        SetDocument,
        SplitRegex,
        SplitIndex,
        SetChunkData,
        CreateChunk,
        ReplaceRegex,
        AddChunkToCollection,
        JoinCollections,
        Merge,
        ForEach,
        Chunk,
        ChunkCollection,
        OrderByChunkIndex,
        GetElement,
        GetCollectionSize,
        Equals,
        Int,
        String,
        Add,
        IntToChunk,
        Set,
        TwoBus,
        ThreeBus,
        FourBus,
        Filter,
        Clear,
        OrderAlphabetical
    }
}