// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RefactorGraph
{
    internal sealed partial class Vsix
    {
        public const string Id = "RefactorGraph.f705a1a6-5207-4496-ad4f-a7b8a52eebd1";
        public const string Name = "RefactorGraph";
        public const string Description = @"Node-based code refactoring tool for C#.";
        public const string Language = "en-US";
        public const string Version = "1.11";
        public const string Author = "ChillPillGames";
        public const string Tags = "Refactoring, Editor, Graph";
    }
}
