// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RefactorGraph
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string RefactorGraphGuidString = "02177524-e6b6-4f79-ac09-eb3608cf2147";
        public static Guid RefactorGraphGuid = new Guid(RefactorGraphGuidString);

        public const string GuidLogoString = "4e1d4f06-7979-4d73-895f-c7847cbc4850";
        public static Guid GuidLogo = new Guid(GuidLogoString);

        public const string GuidPreviewString = "eb4e66eb-3f9d-42f8-be12-e77e394037bb";
        public static Guid GuidPreview = new Guid(GuidPreviewString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ShowRefactorGraphCommand = 0x0100;
        public const int Logo = 0x0001;
        public const int Preview = 0x0001;
    }
}